# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_open', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=50, verbose_name='Nom affich\xe9')),
                ('associated_key', models.CharField(max_length=50, verbose_name='Cl\xe9')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('movie_url', models.URLField()),
                ('description', models.TextField()),
                ('submit_date', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('associated_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioinfuse.AssociatedKey')),
            ],
        ),
        migrations.AddField(
            model_name='associatedkey',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioinfuse.Member'),
        ),
    ]
