# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfuse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('C', 'Concurrent'), ('J', 'Jury'), ('A', 'Admin')], default=0, max_length=1, verbose_name='R\xf4le'),
            preserve_default=False,
        ),
    ]
