# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfuse', '0002_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedkey',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bioinfuse.Challenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='challenge',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='bioinfuse.Challenge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Ouvert'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(verbose_name='Date de d\xe9but'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='stop_date',
            field=models.DateTimeField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('C', 'Concurrent'), ('J', 'Jury'), ('A', 'Admin')], default='C', max_length=1, verbose_name='R\xf4le'),
        ),
    ]
