# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfuse', '0005_auto_20160417_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='subm_start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 14, 19, 38, 58189, tzinfo=utc), verbose_name='Date de d\xe9but de soumission'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='subm_stop_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 14, 19, 38, 58223, tzinfo=utc), verbose_name='Date de fin de soumission'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='subs_start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 14, 19, 38, 58116, tzinfo=utc), verbose_name="Date de d\xe9but d'inscription"),
        ),
        migrations.AddField(
            model_name='challenge',
            name='subs_stop_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 14, 19, 38, 58153, tzinfo=utc), verbose_name="Date de fin d'inscription"),
        ),
        migrations.AlterField(
            model_name='associatedkey',
            name='associated_key',
            field=models.CharField(max_length=50, verbose_name="Cl\xe9 d'association"),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 14, 19, 38, 58019, tzinfo=utc), verbose_name='Date de d\xe9but'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='stop_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 14, 19, 38, 58077, tzinfo=utc), verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='member',
            name='associated_key',
            field=models.CharField(max_length=50, null=True, verbose_name='Cl\xe9 associ\xe9e'),
        ),
        migrations.AlterField(
            model_name='member',
            name='show_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom affich\xe9'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='associated_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bioinfuse.AssociatedKey'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(help_text='Cette description sera aussi utilis\xe9e sur notre compte DailyMotion', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(null=True, verbose_name='Lien vers la vid\xe9o'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publi\xe9'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 14, 19, 38, 60580, tzinfo=utc), help_text='La date doit \xeatre ins\xe9r\xe9e sous forme jj/mm/aaaa hh:mm:ss', verbose_name='Date de soumission'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Ce titre sera aussi utilis\xe9 sur notre compte DailyMotion', max_length=120, verbose_name='Titre'),
        ),
    ]
