# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfuse', '0005_auto_20160417_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='subm_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de d\xe9but de soumission'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='subm_stop_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de fin de soumission'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='subs_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de d\xe9but d'inscription"),
        ),
        migrations.AddField(
            model_name='challenge',
            name='subs_stop_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de fin d'inscription"),
        ),
    ]
