# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfuse', '0006_auto_20160506_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 14, 20, 52, 312480, tzinfo=utc), verbose_name='Date de d\xe9but'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='stop_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 14, 20, 52, 312542, tzinfo=utc), verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subm_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de d\xe9but de soumission'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subm_stop_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de fin de soumission'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subs_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de d\xe9but d'inscription"),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subs_stop_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de fin d'inscription"),
        ),
        migrations.AlterField(
            model_name='movie',
            name='submit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='La date doit \xeatre ins\xe9r\xe9e sous forme jj/mm/aaaa hh:mm:ss', verbose_name='Date de soumission'),
        ),
    ]
