# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfuse', '0006_auto_20160425_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatedkey',
            name='associated_key',
            field=models.CharField(max_length=50, verbose_name="Cl\xe9 d'association"),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subm_start_date',
            field=models.DateTimeField(verbose_name='Date de d\xe9but de soumission'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subm_stop_date',
            field=models.DateTimeField(verbose_name='Date de fin de soumission'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subs_start_date',
            field=models.DateTimeField(verbose_name="Date de d\xe9but d'inscription"),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subs_stop_date',
            field=models.DateTimeField(verbose_name="Date de fin d'inscription"),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(help_text='Cette description sera aussi utilis\xe9e sur notre compte DailyMotion', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(verbose_name='Lien vers la vid\xe9o'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publi\xe9'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='submit_date',
            field=models.DateTimeField(help_text='La date doit \xeatre ins\xe9r\xe9e sous forme jj/mm/aaaa hh:mm:ss', verbose_name='Date de soumission'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Ce titre sera aussi utilis\xe9 sur notre compte DailyMotion', max_length=120, verbose_name='Titre'),
        ),
    ]
