# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfuse', '0007_auto_20160506_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de d\xe9but'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='stop_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de fin'),
        ),
    ]
