# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfuse', '0007_auto_20160427_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='associated_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bioinfuse.AssociatedKey'),
        ),
    ]
