# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfuse', '0008_auto_20160506_1421'),
        ('bioinfuse', '0008_auto_20160501_1631'),
    ]

    operations = [
    ]
