# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfuse', '0011_article_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_note', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=1, verbose_name='Globale')),
                ('artistic_note', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=1, verbose_name='Artistique')),
                ('originality_note', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=1, verbose_name='Originalit\xe9 du sujet')),
                ('investment_note', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=1, verbose_name='Moyens investis')),
                ('take_home_message_note', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=1, verbose_name='Take-home message')),
                ('understandable_note', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=1, verbose_name='Compr\xe9hensible par la cible')),
                ('scientific_note', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=1, verbose_name='Scientifique')),
                ('captive_interest_note', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=1, verbose_name="Captive l'int\xe9r\xeat")),
                ('rigorous_note', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=1, verbose_name='Rigueur scientifique')),
                ('comment', models.TextField(verbose_name='Votre commentaire :')),
                ('id_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioinfuse.Challenge')),
                ('id_jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioinfuse.Member')),
                ('id_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioinfuse.Movie')),
            ],
        ),
    ]
